In [1]:
import pandas as pd
import numpy as np

# Membuat data sampel dengan missing values
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, np.nan, 35, 45, np.nan],
    'Income': [50000, 60000, np.nan, 80000, 90000],
    'Gender': ['F', 'M', np.nan, 'M', 'F']
}

# Membuat dataframe
df = pd.DataFrame(data)

# Menampilkan data
print("Original DataFrame:")
print(df)

# Menghapus baris dengan missing values
df_dropna = df.dropna()
print("\nDataFrame setelah menghapus baris dengan missing values:")
print(df_dropna)

# Mengisi missing values dengan mean (untuk kolom numerik)
df['Age'].fillna(df['Age'].mean(), inplace=True)
df['Income'].fillna(df['Income'].mean(), inplace=True)
print("\nDataFrame setelah mengisi missing values dengan mean:")
print(df)

# Mengisi missing values dengan mode (untuk kolom kategorikal)
df['Gender'].fillna(df['Gender'].mode()[0], inplace=True)
print("\nDataFrame setelah mengisi missing values dengan mode:")
print(df)

# Mengisi missing values dengan metode forward fill
df_ffill = df.fillna(method='ffill')
print("\nDataFrame setelah mengisi missing values dengan forward fill:")
print(df_ffill)

# Mengisi missing values dengan metode backward fill
df_bfill = df.fillna(method='bfill')
print("\nDataFrame setelah mengisi missing values dengan backward fill:")
print(df_bfill)

# Mengisi missing values dengan interpolasi
df_interpolate = df.interpolate(method='linear')
print("\nDataFrame setelah mengisi missing values dengan interpolasi:")
print(df_interpolate)

Original DataFrame:
      Name   Age   Income Gender
0    Alice  25.0  50000.0      F
1      Bob   NaN  60000.0      M
2  Charlie  35.0      NaN    NaN
3    David  45.0  80000.0      M
4      Eve   NaN  90000.0      F

DataFrame setelah menghapus baris dengan missing values:
    Name   Age   Income Gender
0  Alice  25.0  50000.0      F
3  David  45.0  80000.0      M

DataFrame setelah mengisi missing values dengan mean:
      Name   Age   Income Gender
0    Alice  25.0  50000.0      F
1      Bob  35.0  60000.0      M
2  Charlie  35.0  70000.0    NaN
3    David  45.0  80000.0      M
4      Eve  35.0  90000.0      F

DataFrame setelah mengisi missing values dengan mode:
      Name   Age   Income Gender
0    Alice  25.0  50000.0      F
1      Bob  35.0  60000.0      M
2  Charlie  35.0  70000.0      F
3    David  45.0  80000.0      M
4      Eve  35.0  90000.0      F

DataFrame setelah mengisi missing values dengan forward fill:
      Name   Age   Income Gender
0    Alice  25.0  50000.0      F
1      Bob  35.0  60000.0      M
2  Charlie  35.0  70000.0      F
3    David  45.0  80000.0      M
4      Eve  35.0  90000.0      F

DataFrame setelah mengisi missing values dengan backward fill:
      Name   Age   Income Gender
0    Alice  25.0  50000.0      F
1      Bob  35.0  60000.0      M
2  Charlie  35.0  70000.0      F
3    David  45.0  80000.0      M
4      Eve  35.0  90000.0      F

DataFrame setelah mengisi missing values dengan interpolasi:
      Name   Age   Income Gender
0    Alice  25.0  50000.0      F
1      Bob  35.0  60000.0      M
2  Charlie  35.0  70000.0      F
3    David  45.0  80000.0      M
4      Eve  35.0  90000.0      F

C:\Users\galan\AppData\Local\Temp\ipykernel_19444\987479907.py:25: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(), inplace=True)
C:\Users\galan\AppData\Local\Temp\ipykernel_19444\987479907.py:26: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Income'].fillna(df['Income'].mean(), inplace=True)
C:\Users\galan\AppData\Local\Temp\ipykernel_19444\987479907.py:31: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gender'].fillna(df['Gender'].mode()[0], inplace=True)
C:\Users\galan\AppData\Local\Temp\ipykernel_19444\987479907.py:36: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_ffill = df.fillna(method='ffill')
C:\Users\galan\AppData\Local\Temp\ipykernel_19444\987479907.py:41: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_bfill = df.fillna(method='bfill')
C:\Users\galan\AppData\Local\Temp\ipykernel_19444\987479907.py:46: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df_interpolate = df.interpolate(method='linear')